version: "3.9"
services:
  db:
    image: mysql:8.0
    container_name: mysql_container
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=test_database
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password

    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  flask_app:
    build:
      context: .
    container_name: test_tracking
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_NAME: test_database
      DB_USER: user
      DB_PASSWORD: password

volumes:
  db_data:

